version: '3.8'
services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - type: bind
        source: ./data
        target: /data/db

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build: 
      context: ./nginx
      dockerfile: ../nginx/Dockerfile
    ports:
      - "3050:80"
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:nginx-${TAG}  

  api:
    build: 
      context: './server'
      dockerfile: ../server/Dockerfile
    volumes:
      - /shoopp/node_modules
      - ../server:/shoopp
    environment:
      - MONGO_URI=${MONGO_URI}
      - SECRET=${SECRET}
      - TOKEN_KEY=${TOKEN_KEY}
      - VERIFALIA_USER=${VERIFALIA_USER}
      - VERIFALIA_PASS=${VERIFALIA_PASS}
      - PORT=${PORT}
    depends_on:
      - mongodb
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:api-${TAG}

  client:
    build: 
      context: ./client
      dockerfile: ../client/Dockerfile

    volumes:
      - /shoopp/node_modules
      - ../client:/shoopp
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:client-${TAG}

