version: '3.8'
services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - type: bind
        source: ./data
        target: /data/db

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
    image: mynginx:${TAG}  

  api:
    build: 
      dockerfile: Dockerfile
      context: './server'
    volumes:
      - /shoopp/node_modules
      - ./server:/shoopp
    environment:
      - MONGO_URI=${MONGO_URI}
      - SECRET=${SECRET}
      - TOKEN_KEY=${TOKEN_KEY}
      - VERIFALIA_USER=${VERIFALIA_USER}
      - VERIFALIA_PASS=${VERIFALIA_PASS}
      - PORT=${PORT}
    depends_on:
      - mongodb
    image: myapi:${TAG}

  client:
    build: 
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /shoopp/node_modules
      - ./client:/shoopp
    image: myclient:${TAG} 

