apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoopp
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: shoopp
    spec:
    spec:
      automountServiceAccountToken: false 
      containers:
        - name: shoopp
          image: DOCKER_IMAGE 
          ports:
            - containerPort: 3050
          env:
            - name: MONGO_URI
              value: $MONGO_URI
            - name: SECRET
              value: $SECRET
            - name: TOKEN_KEY
              value: $TOKEN_KEY
            - name: VERIFALIA_USER
              value: $VERIFALIA_USER
            - name: VERIFALIA_PASS
              value: $VERIFALIA_PASS
            - name: PORT
              value: $PORT
          resources:
            limits:
              memory: "512Mi"
              cpu: 0.5
